---
title: "Run SPARK-X analysis on scanpy processed FF Endometrial Adenocarcinoma data"
author: Natalie Charitakis
---

```{r}
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
remotes::install_github("xzhoulab/SPARK")
library(SPARK)
```

##Read in csv files
```{r}
obs <- read.csv('obs.csv')
var <- read.csv('/var.csv')
X <- read.csv('X.csv', header=FALSE)
X <- t(X)
#Add in numbers of names for the spot
colnames(X) <- 0:2836
```

##Generate metadata object to feed into Seurat object
```{r}
#get fake cell barcodes
cell_barcodes <- colnames(X)

#need get list of Orig.ident
orig.ident <- replicate(2837, "ff_ovarian_cancer")

#get number of counts per cell
nCount_RNA <- obs["n_counts"]

#get nFeature 
nFeature_RNA <- obs["n_genes"]

#% MT
percent.mt <- obs["pct_counts_mt"]

#only extract clusters once as this will be populated twice in metadata
seurat_clusters <- obs["clusters"]

metadata <- data.frame(orig.ident, nCount_RNA,nFeature_RNA, percent.mt, seurat_clusters)
rownames(metadata) <- cell_barcodes
colnames(metadata) <- c("orig.ident", "nCount_RNA","nFeature_RNA","percent.mt","seurat_clusters")
metadata
```

#Now try creating Seurat object
```{r}
ff_ovarian_cancer_seurat <- CreateSeuratObject(X,
  project = "CreateSeuratObject",
  assay = "RNA",
  names.field = 1,
  meta.data = metadata,
)

#add active assay
ff_ovarian_cancer_seurat@active.assay <- c("RNA")
```

#get spatial coordinates
```{r}
#load in tissue position list
tissue_coordinates <- read.csv('tissue_positions_list.csv',header=FALSE)
colnames(tissue_coordinates) <- c("barcode","tissue","row","col","imagerow","imagecol")
tissue_coordinates

##sort tissue coordinates df by obs barcodes
sorted_barcodes <- obs$X

tissue_coordinates <- tissue_coordinates[match(sorted_barcodes, tissue_coordinates$barcode), ]
rownames(tissue_coordinates) <- tissue_coordinates$barcode
tissue_coordinates = subset(tissue_coordinates, select = -c(barcode)) 
tissue_coordinates

#create scale factors object to add
spot = 188.58137874994503
fiducial = 304.63145798068047
hires = 0.072809346
lowres = 0.021842804
scale_factors <- Seurat::scalefactors(spot=spot,fiducial = fiducial,hires = hires,lowres = lowres)

##add coordinates and name of assay
ff_ovarian_cancer_seurat@images$slice.1 = new(Class="VisiumV1",assay="RNA",key="image_",coordinates=tissue_coordinates,scale.factors=scale_factors)
ff_ovarian_cancer_seurat@images$slice.1@assay <- c("RNA")

```

##Load in same data from scanpy X file as scaled data
```{r}
ff_ovarian_cancer_seurat@assays$RNA@scale.data <- X 
```

#Extract our data with barcodes and information
```{r}
coordinates <- ff_ovarian_cancer_seurat@images$slice.1@coordinates
#Unsure is row and rol or imagerow and imagecol so try both
loc <- coordinates[, c("row","col")]
#change column names
colnames(loc) <- c("x","y")
loc <- as.matrix(loc)
```

#Extract and label counts data
```{r}
##Need count matrix
counts <- as.matrix(ff_ovarian_cancer_seurat@assays$RNA@counts)
```

#Analyse the data with SPARK-X
```{r}
sparkX <- sparkx(counts,loc,numCores=1,option="mixture")
```

#Filter genes by combinedPval then adjusted Pval
```{r}
#these have the gene names and p values
res <- sparkX$res_mtest

#first sort by combined pvalue
res <-  res[order(res$combinedPval),]
write.csv(res,'ff_ovarian_cancer_spark_all_SVGS_adj_pval.csv')

#cut off al genes with adjusted Pval > 0.05
sig_res <- res[res$adjustedPval <= 0.05,]
sig_res

#write this to file
write.csv(sig_res,'ff_ovarian_cancer_spark_sig_SVGS_adj_pval.csv')
```